name: Deploy Site

on:
  push:
    branches:
      - main

jobs:
  deploy:

    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create config.js
        run: |
          echo "const API_KEY = '${{ secrets.GOOGLE_MAPS_API_KEY }}';" > config.js

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .