name: Deploy Site

on:
  push:
    branches:
      - main

jobs:
  deploy:

    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Debug Secret Exists
        run: |
          if [ -z "${{ secrets.GOOGLE_MAPS_API_KEY }}" ]; then
            echo "SECRET IS MISSING"
            exit 1
          else
            echo "SECRET FOUND"
          fi

      - name: Inject API Key
        run: |
          node -e "
            const fs = require('fs');

            const key = process.env.KEY;

            let html = fs.readFileSync('index.html', 'utf8');

            html = html.replace('__API_KEY__', key);

            fs.writeFileSync('index.html', html);

            console.log('API key injected successfully');
          "
        env:
          KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .