name: Deploy Site

on:
  push:
    branches:
      - main

jobs:
  deploy:

    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Inject API Key
        run: |
          sed -i "s|__API_KEY__|${{ secrets.GOOGLE_MAPS_API_KEY }}|g" index.html

      - name: Verify Replacement
        run: |
          grep "maps.googleapis.com" index.html

      - name: Prepare Deploy Folder
        run: |
          mkdir deploy
          rsync -av --exclude=deploy . deploy

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy